# #####################################################################
# @(#)Makefile
# ---------------------------------------------------------------------
# Project Name:           MakeHuman
# Product Home Page:      http://www.makehuman.org/
# SourceForge Home Page:  http://sourceforge.net/projects/makehuman/
# Authors:                Manuel Bastioni, Paolo Colombo, Simone Re, Hans-Peter Dusel
# Copyright(c):           MakeHuman Team 2001-2009
# Licensing:              GPL3 (see also http://makehuman.wiki.sourceforge.net/Licensing)
# Coding Standards:       See http://makehuman.wiki.sourceforge.net/DG_Coding_Standards
# #####################################################################

# --------------------------------------------
# The Sources and Pathes
# --------------------------------------------
OBJPATH  = 

# The Targets
EXE = fixmesh

CCSRCS   = src/dump.cc \
           src/gauss.cc \
           src/group.cc \
           src/main.cc \
           src/mesh.cc \
           src/obj.cc \
           src/vector.cc 
CSRCS    = 

# Mention all include paths
EXTRA_INC_PATHS   = include

# Mention all library paths
EXTRA_LIB_PATHS   = 

# Mention all librarys
EXTRA_LIBS        = 

# Mention all framework paths
EXTRA_FMWK_PATHS  =

# Mention all frameworks
EXTRA_FWMKS       = Carbon 

EXTRADEFINES =

DEPS = $(addsuffix .d,$(basename $(CSRCS) $(CCSRCS)))
OBJS = $(addsuffix .o,$(basename $(CSRCS) $(CCSRCS)))

# --------------------------------------------
# Compiler
# --------------------------------------------
# --------------------------------------------
# Using GNU CC as Toolchain
# --------------------------------------------
CC  = gcc
CCC = g++

# --------------------------------------------
# Linker
# --------------------------------------------
LN       = g++
LIBTOOL  = libtool
LIBFLAGS = -static
LINKFLAGS =
# LINKFLAGS =

# --------------------------------------------
DEPTOOL = g++
# --------------------------------------------
RM      = rm -f
INSTALL = cp

# --------------------------------------------
# Compiler specific flags
# --------------------------------------------
# Use this, if you dont want to check against STRICT ANSI...
#ANSI_STRICTNESS = -ansi -Wall
ANSI_STRICTNESS =

ARCHFLAGS = -arch ppc -arch i386

# For Debugging purposes turn off all optimization
#CFLAGS   = -g $(ANSI_STRICTNESS)
#CCFLAGS  = -g $(ANSI_STRICTNESS)
#OPTFLAGS = -O0

# For Final Release turn on full optimization
CFLAGS   = $(ARCHFLAGS) $(ANSI_STRICTNESS)
CCFLAGS  = $(ARCHFLAGS) $(ANSI_STRICTNESS)
OPTFLAGS = -O4

CCFLAGS += $(foreach file, $(EXTRA_INC_PATHS),  -I $(file))
CFLAGS  += $(foreach file, $(EXTRA_INC_PATHS),  -I $(file))
CCFLAGS += $(foreach file, $(EXTRA_LIB_PATHS),  -L $(file))
CFLAGS  += $(foreach file, $(EXTRA_LIB_PATHS),  -L $(file))
CCFLAGS += $(foreach file, $(EXTRA_FMWK_PATHS), -F $(file))
CFLAGS  += $(foreach file, $(EXTRA_FMWK_PATHS), -F $(file))
LINKFLAGS += $(foreach file, $(EXTRA_LIBS),       -l $(file))
LINKFLAGS += $(foreach file, $(EXTRA_FMWK_PATHS), -F $(file))
LINKFLAGS += $(foreach file, $(EXTRA_FWMKS), -framework $(file))

LINKFLAGS += $(ARCHFLAGS)

# The rule to build the targe(s)
$(EXE) :

# ---------------------------------------------------------------------
# Build C and C++ Objects
# ---------------------------------------------------------------------
.SUFFIXES: .c .cc .cp .cpp .c++ .cxx .h .hh .hp .hpp .h++ .hxx .i .o .gch

%.o : %.cc
	@echo compiling $< to $@ ...
	@$(CCC) -c $(CCFLAGS) $(OPTFLAGS) $(EXTRADEFINES) $< -o $@ 

%.o : %.c
	@echo compiling $< to $@ ...
	@$(CC) -MMD -c $(CFLAGS) $(OPTFLAGS) $(EXTRADEFINES) $< -o $@ 

# ---------------------------------------------------------------------
# Link Object code
# ---------------------------------------------------------------------
# --------------------------------------------
# Build an executeable
# --------------------------------------------
$(EXE) : $(OBJS)
	@echo "Linking $@ ..."
	@$(LN) $(OBJS) $(LINKFLAGS) $(EXTRALIBS) -o $@

# --------------------------------------------
# Build a library
# --------------------------------------------
$(LIB) : $(OBJS)
	@echo "Linking $@ ..."
	@$(LIBTOOL) $(LIBFLAGS) $(OBJS) -o $@
	@$(AR) -rs $@ $(OBJS)


# ---------------------------------------------------------------------
# Cleanup unused stuff
# ---------------------------------------------------------------------
clean:
	$(RM) $(OBJS) $(DEPS) *.obj *~ *.bak core *.gch *%% *~
# ---------------------------------------------------------------------
# Cleanup unused stuff(even harder)
# ---------------------------------------------------------------------
clobber:clean
	$(RM) $(EXE)
	$(RM) *.aux *.lof *.toc *.dvi
	$(RM) .depend
	$(RM) -r .snprj/

# ---------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------
install: $(EXE)
	$(INSTALL) $(EXE) $(HOME)/bin/

# ---------------------------------------------------------------------
# Include dependencies if exists
# ---------------------------------------------------------------------
-include $(DEPS)

