#!/bin/sh

mydir=./

./fixmesh -build -weight 0.35 -zone 2.0 -verbosity 1 -dir $mydir

./fixmesh -fgroup -verbosity 1 -dir $mydir

for file in ../../data/targets/details/*.target
do
	echo $file
	./fixmesh -convert $file -detail 0.7 -verbosity 0 -dir $mydir
done

for file in ../../data/targets/macrodetails/*.target
do
	echo $file
	./fixmesh -convert $file -detail 0.7 -verbosity 0 -dir $mydir
done

for file in ../../data/targets/microdetails/*.target
do
	echo $file
	./fixmesh -convert $file -verbosity 0 -dir $mydir
done

