#!/bin/sh

mydir=./

for file in ../../data/targets/shapes/*.target
do
	echo $file
	./fixmesh -convert $file -detail 0.7 -verbosity 0 -dir $mydir
done


for file in ../../data/targets/shapes/*.vgroup
do
	echo $file
	./fixmesh -vgroup $file -verbosity 0 -dir $mydir
done


