Root Root
Spine1 Spine1
Spine2 Spine2
Spine3 Spine3
Neck Neck
Head Head
Shoulder_L Shoulder_L
UpArm_L UpArm_L
LoArm_L LoArm_L
Hand_L Hand_L
Shoulder_R Shoulder_R
UpArm_R UpArm_R
LoArm_R LoArm_R
Hand_R Hand_R
Hips Hips
Hip_L -
UpLeg_L UpLeg_L
LoLeg_L LoLeg_L
Foot_L Foot_L
Toe_L Toe_L
Hip_R -
UpLeg_R UpLeg_R
LoLeg_R LoLeg_R
Foot_R Foot_R
Toe_R Toe_R
Wrist_L Wrist_L
ElbowPT_L ElbowPT_L
Ankle_L Ankle_L
KneePT_L KneePT_L
Wrist_R Wrist_R
ElbowPT_R ElbowPT_R
Ankle_R Ankle_R
KneePT_R KneePT_R
